// Type-safe wrapper for Wails Go bindings
// These functions are auto-generated by `wails generate module`
// and available on window.go.main.App

declare global {
  interface Window {
    go: {
      app: {
        App: {
          ListNotebooks(): Promise<Notebook[]>
          CreateNotebook(name: string): Promise<Notebook>
          RenameNotebook(id: string, name: string): Promise<void>
          DeleteNotebook(id: string): Promise<void>
          ListPages(notebookID: string): Promise<Page[]>
          CreatePage(notebookID: string, name: string): Promise<Page>
          GetPageState(pageID: string): Promise<PageState>
          RenamePage(id: string, name: string): Promise<void>
          UpdateViewport(pageID: string, x: number, y: number, zoom: number): Promise<void>
          UpdateDrawingData(pageID: string, data: string): Promise<void>
          DeletePage(id: string): Promise<void>
          CreateBlock(pageID: string, blockType: string, x: number, y: number, w: number, h: number): Promise<Block>
          UpdateBlockPosition(blockID: string, x: number, y: number, w: number, h: number): Promise<void>
          UpdateBlockContent(blockID: string, content: string): Promise<void>
          DeleteBlock(blockID: string): Promise<void>
          SaveImageFile(blockID: string, dataURL: string): Promise<string>
          GetImageData(blockID: string): Promise<string>
          OpenBlockInEditor(blockID: string, lineNumber: number): Promise<void>
          PickTextFile(): Promise<string>
          UpdateBlockFilePath(blockID: string, filePath: string): Promise<string>
          ChangeBlockFileExt(blockID: string, newExt: string): Promise<string>
          CreateConnection(pageID: string, fromID: string, toID: string): Promise<Connection>
          UpdateConnection(id: string, label: string, color: string, style: string): Promise<void>
          DeleteConnection(id: string): Promise<void>
          TerminalWrite(data: string): Promise<void>
          TerminalResize(cols: number, rows: number): Promise<void>
          CloseEditor(): Promise<void>
          LoadUndoTree(pageID: string): Promise<UndoTree | null>
          PushUndoNode(pageID: string, nodeID: string, parentID: string, label: string, snapshotJSON: string): Promise<UndoNode>
          GoToUndoNode(pageID: string, nodeID: string): Promise<void>
          RestorePageBlocks(pageID: string, blocks: Block[]): Promise<void>
          // Database plugin
          ListDatabaseConnections(): Promise<DBConnView[]>
          CreateDatabaseConnection(input: CreateDBConnInput): Promise<DBConnView>
          UpdateDatabaseConnection(id: string, input: CreateDBConnInput): Promise<void>
          DeleteDatabaseConnection(id: string): Promise<void>
          TestDatabaseConnection(id: string): Promise<void>
          IntrospectDatabase(connectionID: string): Promise<SchemaInfo>
          ExecuteQuery(blockID: string, connectionID: string, query: string, fetchSize: number): Promise<QueryResultView>
          FetchMoreRows(connectionID: string, fetchSize: number): Promise<QueryResultView>
          GetCachedResult(blockID: string): Promise<QueryResultView | null>
          ClearCachedResult(blockID: string): Promise<void>
          SaveBlockDatabaseConfig(blockID: string, config: string): Promise<void>
          PickDatabaseFile(): Promise<string>
          ApplyMutations(connectionID: string, table: string, mutations: Mutation[]): Promise<MutationResult>
          // Local Database plugin
          CreateLocalDatabase(blockID: string, name: string): Promise<LocalDatabase>
          GetLocalDatabase(blockID: string): Promise<LocalDatabase>
          UpdateLocalDatabaseConfig(dbID: string, configJSON: string): Promise<void>
          RenameLocalDatabase(dbID: string, name: string): Promise<void>
          DeleteLocalDatabase(dbID: string): Promise<void>
          ListLocalDatabases(): Promise<LocalDatabase[]>
          CreateLocalDBRow(dbID: string, dataJSON: string): Promise<LocalDBRow>
          ListLocalDBRows(dbID: string): Promise<LocalDBRow[]>
          UpdateLocalDBRow(rowID: string, dataJSON: string): Promise<void>
          DeleteLocalDBRow(rowID: string): Promise<void>
          DuplicateLocalDBRow(rowID: string): Promise<LocalDBRow>
          ReorderLocalDBRows(dbID: string, rowIDs: string[]): Promise<void>
          BatchUpdateLocalDBRows(dbID: string, mutationsJSON: string): Promise<void>
          GetLocalDatabaseStats(dbID: string): Promise<LocalDBStats>
          // ETL plugin
          ListETLSources(): Promise<ETLSourceSpec[]>
          CreateETLJob(input: ETLJobInput): Promise<ETLSyncJob>
          GetETLJob(id: string): Promise<ETLSyncJob>
          ListETLJobs(): Promise<ETLSyncJob[]>
          UpdateETLJob(id: string, input: ETLJobInput): Promise<void>
          DeleteETLJob(id: string): Promise<void>
          RunETLJob(id: string): Promise<ETLSyncResult>
          PreviewETLSource(sourceType: string, sourceConfigJSON: string): Promise<ETLPreviewResult>
          ListETLRunLogs(jobID: string): Promise<ETLRunLog[]>
          PickETLFile(): Promise<string>
          ListPageDatabaseBlocks(pageID: string): Promise<PageBlockRef[]>
          DiscoverETLSchema(sourceType: string, sourceConfigJSON: string): Promise<ETLSchemaInfo>
          ExecuteHTTPRequest(blockID: string, configJSON: string): Promise<HTTPResponse>
          SaveBlockHTTPConfig(blockID: string, config: string): Promise<void>
          ListPageHTTPBlocks(pageID: string): Promise<PageBlockRef[]>
        }
      }
    }
    runtime: {
      EventsOn(eventName: string, callback: (...args: any[]) => void): () => void
      EventsEmit(eventName: string, ...data: any[]): void
      LogInfo(message: string): void
    }
  }
}

export interface Notebook {
  id: string
  name: string
  icon: string
  createdAt: string
  updatedAt: string
}

export interface Page {
  id: string
  notebookId: string
  name: string
  order: number
  viewportX: number
  viewportY: number
  viewportZoom: number
  drawingData: string
  createdAt: string
  updatedAt: string
}

export interface Block {
  id: string
  pageId: string
  type: 'markdown' | 'drawing' | 'image' | 'database' | 'code' | 'localdb' | 'http'
  x: number
  y: number
  width: number
  height: number
  content: string
  filePath: string
  styleJson: string
  createdAt: string
  updatedAt: string
}

export interface Connection {
  id: string
  pageId: string
  fromBlockId: string
  toBlockId: string
  label: string
  color: string
  style: 'solid' | 'dashed' | 'dotted'
  createdAt: string
  updatedAt: string
}

export interface PageState {
  page: Page
  blocks: Block[]
  connections: Connection[]
}

export interface UndoNode {
  id: string
  pageId: string
  parentId: string | null
  label: string
  snapshotJson: string
  createdAt: string
}

export interface UndoTree {
  nodes: UndoNode[]
  currentId: string
  rootId: string
}

// ── Database Plugin Types ──────────────────────────────────

export interface DBConnView {
  id: string
  name: string
  driver: 'mysql' | 'postgres' | 'mongodb' | 'sqlite'
  host: string
  port: number
  database: string
  username: string
  sslMode: string
}

export interface CreateDBConnInput {
  name: string
  driver: string
  host: string
  port: number
  database: string
  username: string
  password: string
  sslMode: string
}

export interface QueryResultView {
  columns: string[]
  rows: any[][]
  totalRows: number
  hasMore: boolean
  durationMs: number
  error: string
  isWrite: boolean
  affectedRows: number
  query: string
  primaryKeys?: string[]
}

export interface Mutation {
  type: 'update' | 'delete'
  rowKey: Record<string, any>
  changes?: Record<string, any>
}

export interface MutationResult {
  applied: number
  errors?: string[]
}

export interface SchemaInfo {
  tables: TableInfo[]
}

export interface TableInfo {
  name: string
  columns: ColumnInfo[]
}

export interface ColumnInfo {
  name: string
  type: string
}

// ── Local Database Plugin Types ────────────────────────────

export type ColumnType = 'text' | 'number' | 'date' | 'datetime' | 'select' | 'multi-select' | 'checkbox' | 'url' | 'person' | 'timer' | 'formula' | 'relation' | 'rollup' | 'progress' | 'rating'

export interface ColumnDef {
  id: string
  name: string
  type: ColumnType
  width: number
  options?: string[]        // for select / multi-select
  formula?: string          // for formula type
  relationDbId?: string     // for relation type
  rollupRelCol?: string     // for rollup type
  rollupAgg?: string        // sum | avg | count | min | max
}

export interface ViewConfig {
  titleColumn?: string      // column ID used as title in all views
  groupByColumn?: string    // column ID used to group in Kanban
  dateColumn?: string       // column ID used for Calendar placement
  checkboxColumn?: string   // column ID used for List checkbox
}

export interface LocalDatabaseConfig {
  columns: ColumnDef[]
  activeView: string
  viewConfig?: ViewConfig
}

export interface LocalDatabase {
  id: string
  blockId: string
  name: string
  configJson: string
  createdAt: string
  updatedAt: string
}

export interface LocalDBRow {
  id: string
  databaseId: string
  dataJson: string
  sortOrder: number
  createdAt: string
  updatedAt: string
}

export interface LocalDBStats {
  rowCount: number
  lastUpdated: string
}

// ── ETL Plugin Types ──────────────────────────────────────

export interface ETLSourceSpec {
  type: string
  label: string
  icon: string
  configFields: ETLConfigField[]
}

export interface ETLConfigField {
  key: string
  label: string
  type: string
  required: boolean
  options?: string[]
  default?: string
  help?: string
  placeholder?: string
}

export interface ETLJobInput {
  name: string
  sourceType: string
  sourceConfig: Record<string, string>
  transforms: ETLTransformConfig[]
  targetDbId: string
  syncMode: string
  dedupeKey: string
  triggerType: string
  triggerConfig: string
  enabled: boolean
}

export interface ETLTransformConfig {
  type: string
  config: Record<string, string>
}

export interface ETLSyncJob {
  id: string
  name: string
  sourceType: string
  sourceConfig: Record<string, string>
  transforms: ETLTransformConfig[]
  targetDbId: string
  syncMode: string
  dedupeKey: string
  triggerType: string
  triggerConfig: string
  enabled: boolean
  lastRunAt: string
  lastStatus: string
  lastError: string
  createdAt: string
  updatedAt: string
}

export interface ETLSyncResult {
  jobId: string
  status: string
  rowsRead: number
  rowsWritten: number
  duration: number
  error?: string
}

export interface ETLPreviewResult {
  columns: string[]
  rows: Record<string, string>[]
  totalRows: number
}

export interface ETLRunLog {
  id: string
  jobId: string
  startedAt: string
  finishedAt: string
  status: string
  rowsRead: number
  rowsWritten: number
  error?: string
}

export interface ETLSchemaInfo {
  fields: Array<{ name: string; type: string }>
}

export interface PageBlockRef {
  id: string
  name: string
  type: string
}

// ── HTTP Plugin Types ─────────────────────────────────────

export interface HTTPResponse {
  statusCode: number
  statusText: string
  headers: Record<string, string>
  body: string
  durationMs: number
  size: number
}

function getAPI() {
  return window.go.app.App
}

export const api = {
  listNotebooks: () => getAPI().ListNotebooks(),
  createNotebook: (name: string) => getAPI().CreateNotebook(name),
  renameNotebook: (id: string, name: string) => getAPI().RenameNotebook(id, name),
  deleteNotebook: (id: string) => getAPI().DeleteNotebook(id),

  listPages: (notebookID: string) => getAPI().ListPages(notebookID),
  createPage: (notebookID: string, name: string) => getAPI().CreatePage(notebookID, name),
  getPageState: (pageID: string) => getAPI().GetPageState(pageID),
  renamePage: (id: string, name: string) => getAPI().RenamePage(id, name),
  updateViewport: (pageID: string, x: number, y: number, zoom: number) => getAPI().UpdateViewport(pageID, x, y, zoom),
  updateDrawingData: (pageID: string, data: string) => getAPI().UpdateDrawingData(pageID, data),
  deletePage: (id: string) => getAPI().DeletePage(id),

  createBlock: (pageID: string, type: string, x: number, y: number, w: number, h: number) => getAPI().CreateBlock(pageID, type, x, y, w, h),
  updateBlockPosition: (id: string, x: number, y: number, w: number, h: number) => getAPI().UpdateBlockPosition(id, x, y, w, h),
  updateBlockContent: (id: string, content: string) => getAPI().UpdateBlockContent(id, content),
  deleteBlock: (id: string) => getAPI().DeleteBlock(id),
  saveImageFile: (blockID: string, dataURL: string): Promise<string> => getAPI().SaveImageFile(blockID, dataURL),
  getImageData: (blockID: string): Promise<string> => getAPI().GetImageData(blockID),
  openBlockInEditor: (id: string, lineNumber: number) => getAPI().OpenBlockInEditor(id, lineNumber),
  pickTextFile: (): Promise<string> => getAPI().PickTextFile(),
  updateBlockFilePath: (blockID: string, filePath: string): Promise<string> => getAPI().UpdateBlockFilePath(blockID, filePath),
  changeBlockFileExt: (blockID: string, newExt: string): Promise<string> => getAPI().ChangeBlockFileExt(blockID, newExt),

  createConnection: (pageID: string, from: string, to: string) => getAPI().CreateConnection(pageID, from, to),
  updateConnection: (id: string, label: string, color: string, style: string) => getAPI().UpdateConnection(id, label, color, style),
  deleteConnection: (id: string) => getAPI().DeleteConnection(id),

  terminalWrite: (data: string) => getAPI().TerminalWrite(data),
  terminalResize: (cols: number, rows: number) => getAPI().TerminalResize(cols, rows),
  closeEditor: () => getAPI().CloseEditor(),
  loadUndoTree: (pageID: string): Promise<UndoTree | null> => getAPI().LoadUndoTree(pageID),
  pushUndoNode: (pageID: string, nodeID: string, parentID: string, label: string, snapshotJSON: string): Promise<UndoNode> => getAPI().PushUndoNode(pageID, nodeID, parentID, label, snapshotJSON),
  goToUndoNode: (pageID: string, nodeID: string) => getAPI().GoToUndoNode(pageID, nodeID),
  restorePageBlocks: (pageID: string, blocks: Block[]) => getAPI().RestorePageBlocks(pageID, blocks),

  // Database plugin
  listDatabaseConnections: () => getAPI().ListDatabaseConnections(),
  createDatabaseConnection: (input: CreateDBConnInput) => getAPI().CreateDatabaseConnection(input),
  updateDatabaseConnection: (id: string, input: CreateDBConnInput) => getAPI().UpdateDatabaseConnection(id, input),
  deleteDatabaseConnection: (id: string) => getAPI().DeleteDatabaseConnection(id),
  testDatabaseConnection: (id: string) => getAPI().TestDatabaseConnection(id),
  introspectDatabase: (connectionID: string) => getAPI().IntrospectDatabase(connectionID),
  executeQuery: (blockID: string, connectionID: string, query: string, fetchSize: number) => getAPI().ExecuteQuery(blockID, connectionID, query, fetchSize),
  fetchMoreRows: (connectionID: string, fetchSize: number) => getAPI().FetchMoreRows(connectionID, fetchSize),
  getCachedResult: (blockID: string) => getAPI().GetCachedResult(blockID),
  clearCachedResult: (blockID: string) => getAPI().ClearCachedResult(blockID),
  saveBlockDatabaseConfig: (blockID: string, config: string) => getAPI().SaveBlockDatabaseConfig(blockID, config),
  pickDatabaseFile: () => getAPI().PickDatabaseFile(),
  applyMutations: (connectionID: string, table: string, mutations: Mutation[]) => getAPI().ApplyMutations(connectionID, table, mutations),

  // Local Database plugin
  createLocalDatabase: (blockID: string, name: string) => getAPI().CreateLocalDatabase(blockID, name),
  getLocalDatabase: (blockID: string) => getAPI().GetLocalDatabase(blockID),
  updateLocalDatabaseConfig: (dbID: string, configJSON: string) => getAPI().UpdateLocalDatabaseConfig(dbID, configJSON),
  renameLocalDatabase: (dbID: string, name: string) => getAPI().RenameLocalDatabase(dbID, name),
  deleteLocalDatabase: (dbID: string) => getAPI().DeleteLocalDatabase(dbID),
  listLocalDatabases: () => getAPI().ListLocalDatabases(),
  createLocalDBRow: (dbID: string, dataJSON: string) => getAPI().CreateLocalDBRow(dbID, dataJSON),
  listLocalDBRows: (dbID: string) => getAPI().ListLocalDBRows(dbID),
  updateLocalDBRow: (rowID: string, dataJSON: string) => getAPI().UpdateLocalDBRow(rowID, dataJSON),
  deleteLocalDBRow: (rowID: string) => getAPI().DeleteLocalDBRow(rowID),
  duplicateLocalDBRow: (rowID: string) => getAPI().DuplicateLocalDBRow(rowID),
  reorderLocalDBRows: (dbID: string, rowIDs: string[]) => getAPI().ReorderLocalDBRows(dbID, rowIDs),
  batchUpdateLocalDBRows: (dbID: string, mutationsJSON: string) => getAPI().BatchUpdateLocalDBRows(dbID, mutationsJSON),
  getLocalDatabaseStats: (dbID: string) => getAPI().GetLocalDatabaseStats(dbID),

  // ETL plugin
  listETLSources: () => getAPI().ListETLSources(),
  createETLJob: (input: any) => getAPI().CreateETLJob(input),
  getETLJob: (id: string) => getAPI().GetETLJob(id),
  listETLJobs: () => getAPI().ListETLJobs(),
  updateETLJob: (id: string, input: any) => getAPI().UpdateETLJob(id, input),
  deleteETLJob: (id: string) => getAPI().DeleteETLJob(id),
  runETLJob: (id: string) => getAPI().RunETLJob(id),
  previewETLSource: (sourceType: string, sourceConfigJSON: string) => getAPI().PreviewETLSource(sourceType, sourceConfigJSON),
  listETLRunLogs: (jobID: string) => getAPI().ListETLRunLogs(jobID),
  pickETLFile: () => getAPI().PickETLFile(),
  listPageDatabaseBlocks: (pageID: string) => getAPI().ListPageDatabaseBlocks(pageID),
  discoverETLSchema: (sourceType: string, sourceConfigJSON: string) => getAPI().DiscoverETLSchema(sourceType, sourceConfigJSON),

  // HTTP Block
  executeHTTPRequest: (blockID: string, configJSON: string) => getAPI().ExecuteHTTPRequest(blockID, configJSON),
  saveBlockHTTPConfig: (blockID: string, config: string) => getAPI().SaveBlockHTTPConfig(blockID, config),
  listPageHTTPBlocks: (pageID: string) => getAPI().ListPageHTTPBlocks(pageID),
}

export function onEvent(name: string, callback: (...args: any[]) => void): () => void {
  return window.runtime.EventsOn(name, callback)
}
