// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbclient} from '../models';
import {domain} from '../models';
import {app} from '../models';
import {storage} from '../models';

export function ApplyMutations(arg1:string,arg2:string,arg3:Array<dbclient.Mutation>):Promise<dbclient.MutationResult>;

export function ChangeBlockFileExt(arg1:string,arg2:string):Promise<string>;

export function ClearCachedResult(arg1:string):Promise<void>;

export function CloseEditor():Promise<void>;

export function CreateBlock(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<domain.Block>;

export function CreateConnection(arg1:string,arg2:string,arg3:string):Promise<domain.Connection>;

export function CreateDatabaseConnection(arg1:app.CreateDBConnInput):Promise<app.DBConnView>;

export function CreateNotebook(arg1:string):Promise<domain.Notebook>;

export function CreatePage(arg1:string,arg2:string):Promise<domain.Page>;

export function DeleteBlock(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteDatabaseConnection(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function DeletePage(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string,arg4:number):Promise<app.QueryResultView>;

export function FetchMoreRows(arg1:string,arg2:number):Promise<app.QueryResultView>;

export function GetCachedResult(arg1:string):Promise<app.QueryResultView>;

export function GetImageData(arg1:string):Promise<string>;

export function GetPageState(arg1:string):Promise<domain.PageState>;

export function GoToUndoNode(arg1:string,arg2:string):Promise<void>;

export function IntrospectDatabase(arg1:string):Promise<dbclient.SchemaInfo>;

export function ListDatabaseConnections():Promise<Array<app.DBConnView>>;

export function ListNotebooks():Promise<Array<domain.Notebook>>;

export function ListPages(arg1:string):Promise<Array<domain.Page>>;

export function LoadUndoTree(arg1:string):Promise<storage.UndoTree>;

export function OpenBlockInEditor(arg1:string,arg2:number):Promise<void>;

export function PickDatabaseFile():Promise<string>;

export function PickTextFile():Promise<string>;

export function PushUndoNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<storage.UndoNode>;

export function RenameNotebook(arg1:string,arg2:string):Promise<void>;

export function RenamePage(arg1:string,arg2:string):Promise<void>;

export function RestorePageBlocks(arg1:string,arg2:Array<domain.Block>):Promise<void>;

export function SaveBlockDatabaseConfig(arg1:string,arg2:string):Promise<void>;

export function SaveImageFile(arg1:string,arg2:string):Promise<string>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalWrite(arg1:string):Promise<void>;

export function TestDatabaseConnection(arg1:string):Promise<void>;

export function UpdateBlockContent(arg1:string,arg2:string):Promise<void>;

export function UpdateBlockFilePath(arg1:string,arg2:string):Promise<string>;

export function UpdateBlockPosition(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function UpdateConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateDatabaseConnection(arg1:string,arg2:app.CreateDBConnInput):Promise<void>;

export function UpdateDrawingData(arg1:string,arg2:string):Promise<void>;

export function UpdateViewport(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;
