// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMutations(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyMutations'](arg1, arg2, arg3);
}

export function BatchUpdateLocalDBRows(arg1, arg2) {
  return window['go']['app']['App']['BatchUpdateLocalDBRows'](arg1, arg2);
}

export function ChangeBlockFileExt(arg1, arg2) {
  return window['go']['app']['App']['ChangeBlockFileExt'](arg1, arg2);
}

export function ClearCachedResult(arg1) {
  return window['go']['app']['App']['ClearCachedResult'](arg1);
}

export function CloseEditor() {
  return window['go']['app']['App']['CloseEditor']();
}

export function CreateBlock(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CreateBlock'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateConnection'](arg1, arg2, arg3);
}

export function CreateDatabaseConnection(arg1) {
  return window['go']['app']['App']['CreateDatabaseConnection'](arg1);
}

export function CreateETLJob(arg1) {
  return window['go']['app']['App']['CreateETLJob'](arg1);
}

export function CreateLocalDBRow(arg1, arg2) {
  return window['go']['app']['App']['CreateLocalDBRow'](arg1, arg2);
}

export function CreateLocalDatabase(arg1, arg2) {
  return window['go']['app']['App']['CreateLocalDatabase'](arg1, arg2);
}

export function CreateNotebook(arg1) {
  return window['go']['app']['App']['CreateNotebook'](arg1);
}

export function CreatePage(arg1, arg2) {
  return window['go']['app']['App']['CreatePage'](arg1, arg2);
}

export function DeleteBlock(arg1) {
  return window['go']['app']['App']['DeleteBlock'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteDatabaseConnection(arg1) {
  return window['go']['app']['App']['DeleteDatabaseConnection'](arg1);
}

export function DeleteETLJob(arg1) {
  return window['go']['app']['App']['DeleteETLJob'](arg1);
}

export function DeleteLocalDBRow(arg1) {
  return window['go']['app']['App']['DeleteLocalDBRow'](arg1);
}

export function DeleteLocalDatabase(arg1) {
  return window['go']['app']['App']['DeleteLocalDatabase'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['app']['App']['DeleteNotebook'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['app']['App']['DeletePage'](arg1);
}

export function DiscoverETLSchema(arg1, arg2) {
  return window['go']['app']['App']['DiscoverETLSchema'](arg1, arg2);
}

export function DuplicateLocalDBRow(arg1) {
  return window['go']['app']['App']['DuplicateLocalDBRow'](arg1);
}

export function ExecuteHTTPRequest(arg1, arg2) {
  return window['go']['app']['App']['ExecuteHTTPRequest'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2, arg3, arg4);
}

export function FetchMoreRows(arg1, arg2) {
  return window['go']['app']['App']['FetchMoreRows'](arg1, arg2);
}

export function GetCachedResult(arg1) {
  return window['go']['app']['App']['GetCachedResult'](arg1);
}

export function GetETLJob(arg1) {
  return window['go']['app']['App']['GetETLJob'](arg1);
}

export function GetImageData(arg1) {
  return window['go']['app']['App']['GetImageData'](arg1);
}

export function GetLocalDatabase(arg1) {
  return window['go']['app']['App']['GetLocalDatabase'](arg1);
}

export function GetLocalDatabaseStats(arg1) {
  return window['go']['app']['App']['GetLocalDatabaseStats'](arg1);
}

export function GetPageState(arg1) {
  return window['go']['app']['App']['GetPageState'](arg1);
}

export function GoToUndoNode(arg1, arg2) {
  return window['go']['app']['App']['GoToUndoNode'](arg1, arg2);
}

export function IntrospectDatabase(arg1) {
  return window['go']['app']['App']['IntrospectDatabase'](arg1);
}

export function ListDatabaseConnections() {
  return window['go']['app']['App']['ListDatabaseConnections']();
}

export function ListETLJobs() {
  return window['go']['app']['App']['ListETLJobs']();
}

export function ListETLRunLogs(arg1) {
  return window['go']['app']['App']['ListETLRunLogs'](arg1);
}

export function ListETLSources() {
  return window['go']['app']['App']['ListETLSources']();
}

export function ListLocalDBRows(arg1) {
  return window['go']['app']['App']['ListLocalDBRows'](arg1);
}

export function ListLocalDatabases() {
  return window['go']['app']['App']['ListLocalDatabases']();
}

export function ListNotebooks() {
  return window['go']['app']['App']['ListNotebooks']();
}

export function ListPageDatabaseBlocks(arg1) {
  return window['go']['app']['App']['ListPageDatabaseBlocks'](arg1);
}

export function ListPageHTTPBlocks(arg1) {
  return window['go']['app']['App']['ListPageHTTPBlocks'](arg1);
}

export function ListPages(arg1) {
  return window['go']['app']['App']['ListPages'](arg1);
}

export function LoadUndoTree(arg1) {
  return window['go']['app']['App']['LoadUndoTree'](arg1);
}

export function OpenBlockInEditor(arg1, arg2) {
  return window['go']['app']['App']['OpenBlockInEditor'](arg1, arg2);
}

export function PickDatabaseFile() {
  return window['go']['app']['App']['PickDatabaseFile']();
}

export function PickETLFile() {
  return window['go']['app']['App']['PickETLFile']();
}

export function PickTextFile() {
  return window['go']['app']['App']['PickTextFile']();
}

export function PreviewETLSource(arg1, arg2) {
  return window['go']['app']['App']['PreviewETLSource'](arg1, arg2);
}

export function PushUndoNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['PushUndoNode'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameLocalDatabase(arg1, arg2) {
  return window['go']['app']['App']['RenameLocalDatabase'](arg1, arg2);
}

export function RenameNotebook(arg1, arg2) {
  return window['go']['app']['App']['RenameNotebook'](arg1, arg2);
}

export function RenamePage(arg1, arg2) {
  return window['go']['app']['App']['RenamePage'](arg1, arg2);
}

export function ReorderLocalDBRows(arg1, arg2) {
  return window['go']['app']['App']['ReorderLocalDBRows'](arg1, arg2);
}

export function RestorePageBlocks(arg1, arg2) {
  return window['go']['app']['App']['RestorePageBlocks'](arg1, arg2);
}

export function RunETLJob(arg1) {
  return window['go']['app']['App']['RunETLJob'](arg1);
}

export function SaveBlockDatabaseConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveBlockDatabaseConfig'](arg1, arg2);
}

export function SaveBlockHTTPConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveBlockHTTPConfig'](arg1, arg2);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['app']['App']['SaveImageFile'](arg1, arg2);
}

export function TerminalResize(arg1, arg2) {
  return window['go']['app']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalWrite(arg1) {
  return window['go']['app']['App']['TerminalWrite'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['app']['App']['TestDatabaseConnection'](arg1);
}

export function UpdateBlockContent(arg1, arg2) {
  return window['go']['app']['App']['UpdateBlockContent'](arg1, arg2);
}

export function UpdateBlockFilePath(arg1, arg2) {
  return window['go']['app']['App']['UpdateBlockFilePath'](arg1, arg2);
}

export function UpdateBlockPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateBlockPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateConnection(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateConnection'](arg1, arg2, arg3, arg4);
}

export function UpdateDatabaseConnection(arg1, arg2) {
  return window['go']['app']['App']['UpdateDatabaseConnection'](arg1, arg2);
}

export function UpdateDrawingData(arg1, arg2) {
  return window['go']['app']['App']['UpdateDrawingData'](arg1, arg2);
}

export function UpdateETLJob(arg1, arg2) {
  return window['go']['app']['App']['UpdateETLJob'](arg1, arg2);
}

export function UpdateLocalDBRow(arg1, arg2) {
  return window['go']['app']['App']['UpdateLocalDBRow'](arg1, arg2);
}

export function UpdateLocalDatabaseConfig(arg1, arg2) {
  return window['go']['app']['App']['UpdateLocalDatabaseConfig'](arg1, arg2);
}

export function UpdateViewport(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateViewport'](arg1, arg2, arg3, arg4);
}
