// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMutations(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyMutations'](arg1, arg2, arg3);
}

export function ClearCachedResult(arg1) {
  return window['go']['app']['App']['ClearCachedResult'](arg1);
}

export function CloseEditor() {
  return window['go']['app']['App']['CloseEditor']();
}

export function CreateBlock(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CreateBlock'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateConnection'](arg1, arg2, arg3);
}

export function CreateDatabaseConnection(arg1) {
  return window['go']['app']['App']['CreateDatabaseConnection'](arg1);
}

export function CreateNotebook(arg1) {
  return window['go']['app']['App']['CreateNotebook'](arg1);
}

export function CreatePage(arg1, arg2) {
  return window['go']['app']['App']['CreatePage'](arg1, arg2);
}

export function DeleteBlock(arg1) {
  return window['go']['app']['App']['DeleteBlock'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteDatabaseConnection(arg1) {
  return window['go']['app']['App']['DeleteDatabaseConnection'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['app']['App']['DeleteNotebook'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['app']['App']['DeletePage'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2, arg3, arg4);
}

export function FetchMoreRows(arg1, arg2) {
  return window['go']['app']['App']['FetchMoreRows'](arg1, arg2);
}

export function GetCachedResult(arg1) {
  return window['go']['app']['App']['GetCachedResult'](arg1);
}

export function GetImageData(arg1) {
  return window['go']['app']['App']['GetImageData'](arg1);
}

export function GetPageState(arg1) {
  return window['go']['app']['App']['GetPageState'](arg1);
}

export function GoToUndoNode(arg1, arg2) {
  return window['go']['app']['App']['GoToUndoNode'](arg1, arg2);
}

export function IntrospectDatabase(arg1) {
  return window['go']['app']['App']['IntrospectDatabase'](arg1);
}

export function ListDatabaseConnections() {
  return window['go']['app']['App']['ListDatabaseConnections']();
}

export function ListNotebooks() {
  return window['go']['app']['App']['ListNotebooks']();
}

export function ListPages(arg1) {
  return window['go']['app']['App']['ListPages'](arg1);
}

export function LoadUndoTree(arg1) {
  return window['go']['app']['App']['LoadUndoTree'](arg1);
}

export function OpenBlockInEditor(arg1, arg2) {
  return window['go']['app']['App']['OpenBlockInEditor'](arg1, arg2);
}

export function PickDatabaseFile() {
  return window['go']['app']['App']['PickDatabaseFile']();
}

export function PickMarkdownFile() {
  return window['go']['app']['App']['PickMarkdownFile']();
}

export function PushUndoNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['PushUndoNode'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameNotebook(arg1, arg2) {
  return window['go']['app']['App']['RenameNotebook'](arg1, arg2);
}

export function RenamePage(arg1, arg2) {
  return window['go']['app']['App']['RenamePage'](arg1, arg2);
}

export function RestorePageBlocks(arg1, arg2) {
  return window['go']['app']['App']['RestorePageBlocks'](arg1, arg2);
}

export function SaveBlockDatabaseConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveBlockDatabaseConfig'](arg1, arg2);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['app']['App']['SaveImageFile'](arg1, arg2);
}

export function TerminalResize(arg1, arg2) {
  return window['go']['app']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalWrite(arg1) {
  return window['go']['app']['App']['TerminalWrite'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['app']['App']['TestDatabaseConnection'](arg1);
}

export function UpdateBlockContent(arg1, arg2) {
  return window['go']['app']['App']['UpdateBlockContent'](arg1, arg2);
}

export function UpdateBlockFilePath(arg1, arg2) {
  return window['go']['app']['App']['UpdateBlockFilePath'](arg1, arg2);
}

export function UpdateBlockPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateBlockPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateConnection(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateConnection'](arg1, arg2, arg3, arg4);
}

export function UpdateDatabaseConnection(arg1, arg2) {
  return window['go']['app']['App']['UpdateDatabaseConnection'](arg1, arg2);
}

export function UpdateDrawingData(arg1, arg2) {
  return window['go']['app']['App']['UpdateDrawingData'](arg1, arg2);
}

export function UpdateViewport(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateViewport'](arg1, arg2, arg3, arg4);
}
